# Welcome to numpy

In [1]:
import numpy as np

In [2]:
myarr = np.array([[3,6,32,7]],np.int64)

In [3]:
myarr

array([[ 3,  6, 32,  7]], dtype=int64)

In [4]:
myarr[0]

array([ 3,  6, 32,  7], dtype=int64)

In [5]:
myarr[0,1]

6

In [6]:
myarr[0,1] = 45

In [7]:
myarr

array([[ 3, 45, 32,  7]], dtype=int64)

## Array creation: Conversion from other Python structures

In [8]:
listarray = np.array([[1,2,3],[5,8,5],[0,3,1]])

In [9]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [10]:
listarray.dtype

dtype('int32')

In [11]:
listarray.shape

(3, 3)

In [12]:
listarray.size

9

In [13]:
zeros = np.zeros((2,5))

In [14]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
zeros.dtype

dtype('float64')

In [16]:
zeros.shape

(2, 5)

In [17]:
zeros.size

10

In [18]:
rng = np.arange(15)

In [19]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [20]:
lspace = np.linspace(1,50,10)

In [21]:
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [22]:
emp = np.empty((4,6))

In [23]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        6.23047842e-307, 2.22526399e-307, 6.23053614e-307],
       [7.56592338e-307, 1.60216183e-306, 7.56602523e-307,
        3.56043054e-307, 1.37961641e-306, 2.22518251e-306],
       [1.33511969e-306, 6.23037657e-307, 6.23053954e-307,
        9.34609790e-307, 8.45593934e-307, 9.34600963e-307],
       [1.86921143e-306, 6.23061763e-307, 9.34593493e-307,
        7.56602524e-307, 2.22522596e-306, 8.34445562e-308]])

In [24]:
emp_like = np.empty_like(lspace)

In [25]:
emp_like

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [26]:
ide = np.identity(45)

In [27]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [28]:
ide.shape

(45, 45)

In [29]:
arr = np.arange(99)

In [30]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [31]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [32]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [33]:
x = [[1,2,3], [4,5,6], [7,1,0]]

In [34]:
ar = np.array(x)

In [35]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [36]:
ar.sum(axis=0)

array([12,  8,  9])

In [37]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [38]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [39]:
ar.flat

In [40]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [41]:
ar.ndim

2

In [42]:
ar.size

9

In [43]:
ar.nbytes

36

In [44]:
one = np.array([1,3,4,634,2])

In [45]:
one.argmax()

3

In [46]:
one.argmin()

0

In [47]:
one.argsort()

array([0, 4, 1, 2, 3], dtype=int64)

In [48]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [49]:
ar.argmin()

8

In [50]:
ar.argmax()

6

In [51]:
ar.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [52]:
ar.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [53]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [54]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [55]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [56]:
ar.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [57]:
ar.reshape((9,))

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [58]:
ar2 = np.array([[1,2,1], [4,0,6], [8,1,0]])

In [59]:
ar + ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [60]:
ar * ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [61]:
ar2

array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [62]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [63]:
ar.sum()

29

In [64]:
ar.max()

7

In [65]:
ar.min()

0

In [66]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [67]:
np.where(ar>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [68]:
np.count_nonzero(ar)

8

In [69]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [70]:
import sys

In [71]:
py_ar = [0,4,55,2]

In [72]:
np_ar = np.array(py_ar)

In [73]:
sys.getsizeof(1) * len(py_ar)

112

In [74]:
np_ar.itemsize * np_ar.size

16

In [75]:
np_ar.tolist()

[0, 4, 55, 2]